In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [3]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]]) <class 'torch.Tensor'>


In [4]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

In [5]:
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [6]:
torch.rand(3, 3, 3)

tensor([[[ 0.5852,  0.5071,  0.5810],
         [ 0.7933,  0.2726,  0.5493],
         [ 0.4626,  0.5243,  0.6458]],

        [[ 0.6614,  0.0858,  0.6188],
         [ 0.4827,  0.1947,  0.9601],
         [ 0.7045,  0.3956,  0.5414]],

        [[ 0.8306,  0.2103,  0.0887],
         [ 0.2116,  0.5378,  0.5422],
         [ 0.9766,  0.4570,  0.3408]]])

In [7]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)
print(ones_like_zeros)

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [8]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [9]:
ones_like_zeros[:, 0]

tensor([ 1.,  1.,  1.])

In [10]:
x = ones_like_zeros.detach()
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [11]:
x[:, 0] * 5

tensor([ 5.,  5.,  5.])

In [12]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(0.6739)

In [13]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[ 0.4721,  0.4333,  0.3105,  0.3354,  0.6623],
        [ 1.9723,  2.4532,  1.1578,  2.0076,  1.9143],
        [ 1.4650,  1.5788,  0.6487,  1.3169,  1.0851],
        [ 0.9268,  1.1194,  0.6803,  0.8388,  1.1580],
        [ 0.7882,  1.1985,  0.3515,  1.1138,  0.6279]])